#include "EditorApplication.h"
#include "Applications/Shared/_AutoGenerated/ToolsTypeRegistration.h"
#include "Tools/UI/Widgets/IconWidgets.h"

//-------------------------------------------------------------------------

namespace KRG
{
    namespace Editor
    {
        EditorApplication::EditorApplication( int argc, char* argv[] )
            : Tools::Application( argc, argv )
            , m_mapEditor( m_typeRegistry )
        {
            m_applicationName = "Kruger Editor";
            m_applicationIconPath = ":/KRG/Editor.png";
            m_applicationVersion = "0.0";
            //m_splashScreenPath = ":/KRG/EditorSplashScreen.png";
        }

        bool EditorApplication::Initialize()
        {
            AutoGenerated::RegisterTypes( m_typeRegistry );

            //-------------------------------------------------------------------------

            m_pMainMenu = new QMenuBar();

            auto pLayout = new QHBoxLayout( m_pWindow->GetTitleBarContentWidgetLeft() );
            pLayout->setContentsMargins( 0, 0, 0, 0 );
            pLayout->setSpacing( 0 );
            pLayout->addWidget( m_pMainMenu, 0 );

            //-------------------------------------------------------------------------

            m_pMainDockManager = new ads::CDockManager();
            m_pMainDockManager->setStyleSheet( "" );

            auto pMainLayout = new QVBoxLayout( m_pWindow->GetMainContentWidget() );
            pMainLayout->setContentsMargins( 0, 0, 0, 0 );
            pMainLayout->addWidget( m_pMainDockManager );

            //-------------------------------------------------------------------------

            EditorContext context;
            context.m_pDockManager = m_pMainDockManager;
            context.m_pMainMenu = m_pMainMenu;

            m_mapEditor.Initialize( context );

            return true;
        }

        void EditorApplication::Shutdown()
        {
            m_mapEditor.Shutdown();

            //-------------------------------------------------------------------------

            AutoGenerated::UnregisterTypes( m_typeRegistry );
        }
    }
}