//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "E:\Git\KRG\Code\Engine\Physics\_Module\_AutoGenerated\1978636638.h"

//-------------------------------------------------------------------------
// Enum Helper: KRG::Physics::PhysicsCombineMode
//-------------------------------------------------------------------------

namespace KRG
{
    namespace TypeSystem
    {
        namespace EnumHelpers
        {
            void EnumHelper_KRG_Physics_PhysicsCombineMode::RegisterEnum( TypeSystem::TypeRegistry& typeRegistry )
            {
                TypeSystem::TypeInfo typeInfo;
                typeInfo.m_ID = TypeSystem::TypeID( "KRG::Physics::PhysicsCombineMode" );
                typeInfo.m_size = sizeof( KRG::Physics::PhysicsCombineMode );
                typeInfo.m_alignment = alignof( KRG::Physics::PhysicsCombineMode );
                typeRegistry.RegisterType( typeInfo );

                TypeSystem::EnumInfo enumInfo;
                enumInfo.m_ID = TypeSystem::TypeID( "KRG::Physics::PhysicsCombineMode" );
                enumInfo.m_underlyingType = TypeSystem::CoreTypes::Int32;
                enumInfo.m_constants.insert( TPair<StringID, int64>( StringID( "Max" ), 3 ) );
                enumInfo.m_constants.insert( TPair<StringID, int64>( StringID( "Average" ), 0 ) );
                enumInfo.m_constants.insert( TPair<StringID, int64>( StringID( "Multiply" ), 2 ) );
                enumInfo.m_constants.insert( TPair<StringID, int64>( StringID( "Min" ), 1 ) );

                typeRegistry.RegisterEnum( enumInfo );
            }

            void EnumHelper_KRG_Physics_PhysicsCombineMode::UnregisterEnum( TypeSystem::TypeRegistry& typeRegistry )
            {
                auto const ID = TypeSystem::TypeID( "KRG::Physics::PhysicsCombineMode" );
                typeRegistry.UnregisterType( ID );
                typeRegistry.UnregisterEnum( ID );
            }
        }
    }
}

//-------------------------------------------------------------------------
// TypeHelper: KRG::Physics::PhysicsMaterialSettings
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Physics::PhysicsMaterialSettings::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Physics::PhysicsMaterialSettings>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Physics::PhysicsMaterialSettings> TTypeHelper<KRG::Physics::PhysicsMaterialSettings>::StaticTypeHelper;
        }
    }
}
