//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "E:\Git\KRG\Code\Engine\Physics\_Module\Module.h"
#include "System/Resource/ResourceSystem.h"
#include "E:\Git\KRG\Code\Engine\Physics\_Module\_AutoGenerated\1074282608.cpp"
#include "E:\Git\KRG\Code\Engine\Physics\_Module\_AutoGenerated\1908063145.cpp"
#include "E:\Git\KRG\Code\Engine\Physics\_Module\_AutoGenerated\1978636638.cpp"
#include "E:\Git\KRG\Code\Engine\Physics\_Module\_AutoGenerated\2213392133.cpp"
#include "E:\Git\KRG\Code\Engine\Physics\_Module\_AutoGenerated\2223379098.cpp"
#include "E:\Git\KRG\Code\Engine\Physics\_Module\_AutoGenerated\2430320459.cpp"
#include "E:\Git\KRG\Code\Engine\Physics\_Module\_AutoGenerated\2449110164.cpp"
#include "E:\Git\KRG\Code\Engine\Physics\_Module\_AutoGenerated\2612964879.cpp"
#include "E:\Git\KRG\Code\Engine\Physics\_Module\_AutoGenerated\2728660727.cpp"
#include "E:\Git\KRG\Code\Engine\Physics\_Module\_AutoGenerated\2940388832.cpp"
#include "E:\Git\KRG\Code\Engine\Physics\_Module\_AutoGenerated\4075904602.cpp"

//-------------------------------------------------------------------------

void KRG::Physics::EngineModule::RegisterTypes( TypeSystem::TypeRegistry& typeRegistry )
{
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Physics::PhysicsComponent>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Physics::PhysicsMeshComponent>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Physics::PhysicsDebugView>::RegisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Physics_PhysicsCombineMode::RegisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Physics::PhysicsMaterialSettings>::RegisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Physics_ActorType::RegisterEnum( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Physics_ShapeType::RegisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Physics::PhysicsCapsuleComponent>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Physics::PhysicsBoxComponent>::RegisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Physics_Layers::RegisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Physics::PhysicsWorldSystem>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Physics::PhysicsSphereComponent>::RegisterType( typeRegistry );
}

void KRG::Physics::EngineModule::UnregisterTypes( TypeSystem::TypeRegistry& typeRegistry )
{
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Physics::PhysicsSphereComponent>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Physics::PhysicsWorldSystem>::UnregisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Physics_Layers::UnregisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Physics::PhysicsBoxComponent>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Physics::PhysicsCapsuleComponent>::UnregisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Physics_ShapeType::UnregisterEnum( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Physics_ActorType::UnregisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Physics::PhysicsMaterialSettings>::UnregisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Physics_PhysicsCombineMode::UnregisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Physics::PhysicsDebugView>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Physics::PhysicsMeshComponent>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Physics::PhysicsComponent>::UnregisterType( typeRegistry );
}

