//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "D:\Kruger\Code\Engine\Physics\_Module\Module.h"
#include "System/Resource/ResourceSystem.h"
#include "D:\Kruger\Code\Engine\Physics\_Module\_AutoGenerated\2197553932.cpp"
#include "D:\Kruger\Code\Engine\Physics\_Module\_AutoGenerated\3942467760.cpp"

//-------------------------------------------------------------------------

void KRG::Physics::EngineModule::RegisterTypes( TypeSystem::TypeRegistry& typeRegistry )
{
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Physics::PhysicsGeometryComponent>::RegisterType( typeRegistry );
}

void KRG::Physics::EngineModule::UnregisterTypes( TypeSystem::TypeRegistry& typeRegistry )
{
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Physics::PhysicsGeometryComponent>::UnregisterType( typeRegistry );
}

