//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "D:\Kruger\Code\Engine\Physics\_Module\Module.h"
#include "System/Resource/ResourceSystem.h"
#include "D:\Kruger\Code\Engine\Physics\_Module\_AutoGenerated\1459547360.cpp"
#include "D:\Kruger\Code\Engine\Physics\_Module\_AutoGenerated\1504628824.cpp"
#include "D:\Kruger\Code\Engine\Physics\_Module\_AutoGenerated\2163026996.cpp"
#include "D:\Kruger\Code\Engine\Physics\_Module\_AutoGenerated\3124175342.cpp"
#include "D:\Kruger\Code\Engine\Physics\_Module\_AutoGenerated\3925828852.cpp"
#include "D:\Kruger\Code\Engine\Physics\_Module\_AutoGenerated\4213423602.cpp"

//-------------------------------------------------------------------------

void KRG::Physics::EngineModule::RegisterTypes( TypeSystem::TypeRegistry& typeRegistry )
{
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Physics::PhysicsShapeComponent>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Physics::PhysicsMeshComponent>::RegisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Physics_PhysicMaterialCombineMode::RegisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Physics::PhysicsMaterialSettings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Physics::PhysicsCapsuleComponent>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Physics::PhysicsBoxComponent>::RegisterType( typeRegistry );
}

void KRG::Physics::EngineModule::UnregisterTypes( TypeSystem::TypeRegistry& typeRegistry )
{
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Physics::PhysicsBoxComponent>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Physics::PhysicsCapsuleComponent>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Physics::PhysicsMaterialSettings>::UnregisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Physics_PhysicMaterialCombineMode::UnregisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Physics::PhysicsMeshComponent>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Physics::PhysicsShapeComponent>::UnregisterType( typeRegistry );
}

