//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "E:\Git\KRG\Code\Tools\Render\_Module\_AutoGenerated\1006278014.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::Render::MaterialResourceDescriptor
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Render::MaterialResourceDescriptor::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Render::MaterialResourceDescriptor>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Render::MaterialResourceDescriptor> TTypeHelper<KRG::Render::MaterialResourceDescriptor>::StaticTypeHelper;
        }
    }
}
