//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "d:\Kruger\Code\Tools\Render\_Module\_AutoGenerated\193212650.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::Render::SkeletalMeshResourceDescriptor
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Render::SkeletalMeshResourceDescriptor::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Render::SkeletalMeshResourceDescriptor>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Render::SkeletalMeshResourceDescriptor> TTypeHelper<KRG::Render::SkeletalMeshResourceDescriptor>::StaticTypeHelper;
        }
    }
}
