//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "D:\Kruger\Code\Tools\Render\_Module\_AutoGenerated\632646782.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::Render::StaticMeshResourceDescriptor
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Render::StaticMeshResourceDescriptor::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            void const* TTypeHelper<KRG::Render::StaticMeshResourceDescriptor>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Render::StaticMeshResourceDescriptor> TTypeHelper<KRG::Render::StaticMeshResourceDescriptor>::StaticTypeHelper;
        }
    }
}
