//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "D:\Kruger\Code\Game\Core\_Module\_AutoGenerated\1326117132.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::CustomizerTestSystem
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::CustomizerTestSystem::StaticTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            void const* TTypeHelper<KRG::CustomizerTestSystem>::DefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::CustomizerTestSystem> TTypeHelper<KRG::CustomizerTestSystem>::StaticTypeHelper;
        }
    }
}
