//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "d:\Kruger\Code\Game\Core\_Module\_AutoGenerated\1326117132.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::CustomizerTestSystem
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::CustomizerTestSystem::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::CustomizerTestSystem>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::CustomizerTestSystem> TTypeHelper<KRG::CustomizerTestSystem>::StaticTypeHelper;
        }
    }
}
