//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "D:\Kruger\Code\Game\Core\_Module\_AutoGenerated\1784434565.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::DefaultPlayerController
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::DefaultPlayerController::TypeInfoPtr = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            void const* TTypeHelper<KRG::DefaultPlayerController>::DefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::DefaultPlayerController> TTypeHelper<KRG::DefaultPlayerController>::StaticTypeHelper;
        }
    }
}
