//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "E:\Git\KRG\Code\Tools\Physics\_Module\_AutoGenerated\2511172527.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::Physics::PhysicsMaterialDatabaseResourceDescriptor
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Physics::PhysicsMaterialDatabaseResourceDescriptor::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Physics::PhysicsMaterialDatabaseResourceDescriptor>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Physics::PhysicsMaterialDatabaseResourceDescriptor> TTypeHelper<KRG::Physics::PhysicsMaterialDatabaseResourceDescriptor>::StaticTypeHelper;
        }
    }
}
