//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "E:\Git\KRG\Code\Tools\Physics\_Module\_AutoGenerated\293123586.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::Physics::PhysicsMeshResourceDescriptor
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Physics::PhysicsMeshResourceDescriptor::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Physics::PhysicsMeshResourceDescriptor>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Physics::PhysicsMeshResourceDescriptor> TTypeHelper<KRG::Physics::PhysicsMeshResourceDescriptor>::StaticTypeHelper;
        }
    }
}
