//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "D:\Kruger\Code\Compilers\Entity\_Module\_AutoGenerated\3282192230.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::EntityModel::NavmeshResourceDescriptor
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::EntityModel::NavmeshResourceDescriptor::StaticTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            void const* TTypeHelper<KRG::EntityModel::NavmeshResourceDescriptor>::DefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::EntityModel::NavmeshResourceDescriptor> TTypeHelper<KRG::EntityModel::NavmeshResourceDescriptor>::StaticTypeHelper;
        }
    }
}
