//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "D:\Kruger\Code\Compilers\Render\_Module\_AutoGenerated\1650622419.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::Render::MaterialResourceDescriptor
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Render::MaterialResourceDescriptor::TypeInfoPtr = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            void const* TTypeHelper<KRG::Render::MaterialResourceDescriptor>::DefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Render::MaterialResourceDescriptor> TTypeHelper<KRG::Render::MaterialResourceDescriptor>::StaticTypeHelper;
        }
    }
}
