//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "D:\Kruger\Code\Compilers\Render\_Module\_AutoGenerated\1739523965.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::Render::SkeletalMeshResourceDescriptor
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Render::SkeletalMeshResourceDescriptor::TypeInfoPtr = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            void const* TTypeHelper<KRG::Render::SkeletalMeshResourceDescriptor>::DefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Render::SkeletalMeshResourceDescriptor> TTypeHelper<KRG::Render::SkeletalMeshResourceDescriptor>::StaticTypeHelper;
        }
    }
}
