//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "D:\Kruger\Code\Compilers\Render\_Module\_AutoGenerated\2261760404.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::Render::ShaderResourceDescriptor
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Render::ShaderResourceDescriptor::TypeInfoPtr = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            void const* TTypeHelper<KRG::Render::ShaderResourceDescriptor>::DefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Render::ShaderResourceDescriptor> TTypeHelper<KRG::Render::ShaderResourceDescriptor>::StaticTypeHelper;
        }
    }
}
