//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "D:\Kruger\Code\Compilers\Render\_Module\_AutoGenerated\411857634.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::Render::MeshResourceDescriptor
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Render::MeshResourceDescriptor::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            void const* TTypeHelper<KRG::Render::MeshResourceDescriptor>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Render::MeshResourceDescriptor> TTypeHelper<KRG::Render::MeshResourceDescriptor>::StaticTypeHelper;
        }
    }
}
