//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\1084810004.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::ControlParameterBool::Settings
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::ControlParameterBool::Settings::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            void const* TTypeHelper<KRG::Animation::Graph::ControlParameterBool::Settings>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::ControlParameterBool::Settings> TTypeHelper<KRG::Animation::Graph::ControlParameterBool::Settings>::StaticTypeHelper;
        }
    }
}

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::ControlParameterID::Settings
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::ControlParameterID::Settings::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            void const* TTypeHelper<KRG::Animation::Graph::ControlParameterID::Settings>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::ControlParameterID::Settings> TTypeHelper<KRG::Animation::Graph::ControlParameterID::Settings>::StaticTypeHelper;
        }
    }
}

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::ControlParameterInt::Settings
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::ControlParameterInt::Settings::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            void const* TTypeHelper<KRG::Animation::Graph::ControlParameterInt::Settings>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::ControlParameterInt::Settings> TTypeHelper<KRG::Animation::Graph::ControlParameterInt::Settings>::StaticTypeHelper;
        }
    }
}

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::ControlParameterFloat::Settings
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::ControlParameterFloat::Settings::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            void const* TTypeHelper<KRG::Animation::Graph::ControlParameterFloat::Settings>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::ControlParameterFloat::Settings> TTypeHelper<KRG::Animation::Graph::ControlParameterFloat::Settings>::StaticTypeHelper;
        }
    }
}

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::ControlParameterVector::Settings
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::ControlParameterVector::Settings::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            void const* TTypeHelper<KRG::Animation::Graph::ControlParameterVector::Settings>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::ControlParameterVector::Settings> TTypeHelper<KRG::Animation::Graph::ControlParameterVector::Settings>::StaticTypeHelper;
        }
    }
}

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::ControlParameterTarget::Settings
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::ControlParameterTarget::Settings::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            void const* TTypeHelper<KRG::Animation::Graph::ControlParameterTarget::Settings>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::ControlParameterTarget::Settings> TTypeHelper<KRG::Animation::Graph::ControlParameterTarget::Settings>::StaticTypeHelper;
        }
    }
}

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::ControlParameterBoneMask::Settings
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::ControlParameterBoneMask::Settings::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            void const* TTypeHelper<KRG::Animation::Graph::ControlParameterBoneMask::Settings>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::ControlParameterBoneMask::Settings> TTypeHelper<KRG::Animation::Graph::ControlParameterBoneMask::Settings>::StaticTypeHelper;
        }
    }
}

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::VirtualParameterBool::Settings
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::VirtualParameterBool::Settings::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            void const* TTypeHelper<KRG::Animation::Graph::VirtualParameterBool::Settings>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::VirtualParameterBool::Settings> TTypeHelper<KRG::Animation::Graph::VirtualParameterBool::Settings>::StaticTypeHelper;
        }
    }
}

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::VirtualParameterID::Settings
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::VirtualParameterID::Settings::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            void const* TTypeHelper<KRG::Animation::Graph::VirtualParameterID::Settings>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::VirtualParameterID::Settings> TTypeHelper<KRG::Animation::Graph::VirtualParameterID::Settings>::StaticTypeHelper;
        }
    }
}

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::VirtualParameterInt::Settings
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::VirtualParameterInt::Settings::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            void const* TTypeHelper<KRG::Animation::Graph::VirtualParameterInt::Settings>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::VirtualParameterInt::Settings> TTypeHelper<KRG::Animation::Graph::VirtualParameterInt::Settings>::StaticTypeHelper;
        }
    }
}

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::VirtualParameterFloat::Settings
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::VirtualParameterFloat::Settings::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            void const* TTypeHelper<KRG::Animation::Graph::VirtualParameterFloat::Settings>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::VirtualParameterFloat::Settings> TTypeHelper<KRG::Animation::Graph::VirtualParameterFloat::Settings>::StaticTypeHelper;
        }
    }
}

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::VirtualParameterVector::Settings
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::VirtualParameterVector::Settings::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            void const* TTypeHelper<KRG::Animation::Graph::VirtualParameterVector::Settings>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::VirtualParameterVector::Settings> TTypeHelper<KRG::Animation::Graph::VirtualParameterVector::Settings>::StaticTypeHelper;
        }
    }
}

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::VirtualParameterTarget::Settings
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::VirtualParameterTarget::Settings::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            void const* TTypeHelper<KRG::Animation::Graph::VirtualParameterTarget::Settings>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::VirtualParameterTarget::Settings> TTypeHelper<KRG::Animation::Graph::VirtualParameterTarget::Settings>::StaticTypeHelper;
        }
    }
}

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::VirtualParameterBoneMask::Settings
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::VirtualParameterBoneMask::Settings::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            void const* TTypeHelper<KRG::Animation::Graph::VirtualParameterBoneMask::Settings>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::VirtualParameterBoneMask::Settings> TTypeHelper<KRG::Animation::Graph::VirtualParameterBoneMask::Settings>::StaticTypeHelper;
        }
    }
}
