//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "d:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\1181083934.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::LayerBlendNode::Settings
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::LayerBlendNode::Settings::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Animation::Graph::LayerBlendNode::Settings>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::LayerBlendNode::Settings> TTypeHelper<KRG::Animation::Graph::LayerBlendNode::Settings>::StaticTypeHelper;
        }
    }
}
