//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "E:\Git\KRG\Code\Engine\Animation\_Module\_AutoGenerated\1718865734.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::IDEvent
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::IDEvent::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Animation::IDEvent>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::IDEvent> TTypeHelper<KRG::Animation::IDEvent>::StaticTypeHelper;
        }
    }
}
