//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\2450972253.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::SpeedScaleNode::Settings
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::SpeedScaleNode::Settings::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            void const* TTypeHelper<KRG::Animation::Graph::SpeedScaleNode::Settings>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::SpeedScaleNode::Settings> TTypeHelper<KRG::Animation::Graph::SpeedScaleNode::Settings>::StaticTypeHelper;
        }
    }
}

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::VelocityBasedSpeedScaleNode::Settings
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::VelocityBasedSpeedScaleNode::Settings::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            void const* TTypeHelper<KRG::Animation::Graph::VelocityBasedSpeedScaleNode::Settings>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::VelocityBasedSpeedScaleNode::Settings> TTypeHelper<KRG::Animation::Graph::VelocityBasedSpeedScaleNode::Settings>::StaticTypeHelper;
        }
    }
}
