//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "E:\Git\KRG\Code\Engine\Animation\_Module\_AutoGenerated\2615118216.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::GraphNode::Settings
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::GraphNode::Settings::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Animation::Graph::GraphNode::Settings>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::GraphNode::Settings> TTypeHelper<KRG::Animation::Graph::GraphNode::Settings>::StaticTypeHelper;
        }
    }
}
