//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "d:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\2659714809.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::IsTargetSetNode::Settings
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::IsTargetSetNode::Settings::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Animation::Graph::IsTargetSetNode::Settings>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::IsTargetSetNode::Settings> TTypeHelper<KRG::Animation::Graph::IsTargetSetNode::Settings>::StaticTypeHelper;
        }
    }
}

//-------------------------------------------------------------------------
// Enum Helper: KRG::Animation::Graph::TargetInfoNode::Info
//-------------------------------------------------------------------------

namespace KRG
{
    namespace TypeSystem
    {
        namespace EnumHelpers
        {
            void EnumHelper_KRG_Animation_Graph_TargetInfoNode_Info::RegisterEnum( TypeSystem::TypeRegistry& typeRegistry )
            {
                TypeSystem::TypeInfo typeInfo;
                typeInfo.m_ID = TypeSystem::TypeID( "KRG::Animation::Graph::TargetInfoNode::Info" );
                typeInfo.m_size = sizeof( KRG::Animation::Graph::TargetInfoNode::Info );
                typeInfo.m_alignment = alignof( KRG::Animation::Graph::TargetInfoNode::Info );
                typeRegistry.RegisterType( typeInfo );

                TypeSystem::EnumInfo enumInfo;
                enumInfo.m_ID = TypeSystem::TypeID( "KRG::Animation::Graph::TargetInfoNode::Info" );
                enumInfo.m_underlyingType = TypeSystem::CoreTypes::Int32;
                enumInfo.m_constants.insert( TPair<StringID, int64>( StringID( "AngleHorizontal" ), 0 ) );
                enumInfo.m_constants.insert( TPair<StringID, int64>( StringID( "DeltaOrientationY" ), 6 ) );
                enumInfo.m_constants.insert( TPair<StringID, int64>( StringID( "DeltaOrientationX" ), 5 ) );
                enumInfo.m_constants.insert( TPair<StringID, int64>( StringID( "DistanceVerticalOnly" ), 4 ) );
                enumInfo.m_constants.insert( TPair<StringID, int64>( StringID( "DistanceHorizontalOnly" ), 3 ) );
                enumInfo.m_constants.insert( TPair<StringID, int64>( StringID( "AngleVertical" ), 1 ) );
                enumInfo.m_constants.insert( TPair<StringID, int64>( StringID( "Distance" ), 2 ) );
                enumInfo.m_constants.insert( TPair<StringID, int64>( StringID( "DeltaOrientationZ" ), 7 ) );

                typeRegistry.RegisterEnum( enumInfo );
            }

            void EnumHelper_KRG_Animation_Graph_TargetInfoNode_Info::UnregisterEnum( TypeSystem::TypeRegistry& typeRegistry )
            {
                auto const ID = TypeSystem::TypeID( "KRG::Animation::Graph::TargetInfoNode::Info" );
                typeRegistry.UnregisterType( ID );
                typeRegistry.UnregisterEnum( ID );
            }
        }
    }
}

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::TargetInfoNode::Settings
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::TargetInfoNode::Settings::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Animation::Graph::TargetInfoNode::Settings>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::TargetInfoNode::Settings> TTypeHelper<KRG::Animation::Graph::TargetInfoNode::Settings>::StaticTypeHelper;
        }
    }
}

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::TargetOffsetNode::Settings
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::TargetOffsetNode::Settings::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Animation::Graph::TargetOffsetNode::Settings>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::TargetOffsetNode::Settings> TTypeHelper<KRG::Animation::Graph::TargetOffsetNode::Settings>::StaticTypeHelper;
        }
    }
}
