//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "E:\Git\KRG\Code\Engine\Animation\_Module\_AutoGenerated\3684538172.h"

//-------------------------------------------------------------------------
// Enum Helper: KRG::Animation::Graph::VectorInfoNode::Info
//-------------------------------------------------------------------------

namespace KRG
{
    namespace TypeSystem
    {
        namespace EnumHelpers
        {
            void EnumHelper_KRG_Animation_Graph_VectorInfoNode_Info::RegisterEnum( TypeSystem::TypeRegistry& typeRegistry )
            {
                TypeSystem::TypeInfo typeInfo;
                typeInfo.m_ID = TypeSystem::TypeID( "KRG::Animation::Graph::VectorInfoNode::Info" );
                typeInfo.m_size = sizeof( KRG::Animation::Graph::VectorInfoNode::Info );
                typeInfo.m_alignment = alignof( KRG::Animation::Graph::VectorInfoNode::Info );
                typeRegistry.RegisterType( typeInfo );

                TypeSystem::EnumInfo enumInfo;
                enumInfo.m_ID = TypeSystem::TypeID( "KRG::Animation::Graph::VectorInfoNode::Info" );
                enumInfo.m_underlyingType = TypeSystem::CoreTypes::Uint8;
                enumInfo.m_constants.insert( TPair<StringID, int64>( StringID( "Y" ), 1 ) );
                enumInfo.m_constants.insert( TPair<StringID, int64>( StringID( "SizeVertical" ), 8 ) );
                enumInfo.m_constants.insert( TPair<StringID, int64>( StringID( "SizeHorizontal" ), 7 ) );
                enumInfo.m_constants.insert( TPair<StringID, int64>( StringID( "AngleHorizontal" ), 5 ) );
                enumInfo.m_constants.insert( TPair<StringID, int64>( StringID( "Z" ), 2 ) );
                enumInfo.m_constants.insert( TPair<StringID, int64>( StringID( "Length" ), 4 ) );
                enumInfo.m_constants.insert( TPair<StringID, int64>( StringID( "W" ), 3 ) );
                enumInfo.m_constants.insert( TPair<StringID, int64>( StringID( "AngleVertical" ), 6 ) );
                enumInfo.m_constants.insert( TPair<StringID, int64>( StringID( "X" ), 0 ) );

                typeRegistry.RegisterEnum( enumInfo );
            }

            void EnumHelper_KRG_Animation_Graph_VectorInfoNode_Info::UnregisterEnum( TypeSystem::TypeRegistry& typeRegistry )
            {
                auto const ID = TypeSystem::TypeID( "KRG::Animation::Graph::VectorInfoNode::Info" );
                typeRegistry.UnregisterType( ID );
                typeRegistry.UnregisterEnum( ID );
            }
        }
    }
}

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::VectorInfoNode::Settings
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::VectorInfoNode::Settings::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Animation::Graph::VectorInfoNode::Settings>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::VectorInfoNode::Settings> TTypeHelper<KRG::Animation::Graph::VectorInfoNode::Settings>::StaticTypeHelper;
        }
    }
}

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::VectorNegateNode::Settings
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::VectorNegateNode::Settings::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Animation::Graph::VectorNegateNode::Settings>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::VectorNegateNode::Settings> TTypeHelper<KRG::Animation::Graph::VectorNegateNode::Settings>::StaticTypeHelper;
        }
    }
}
