//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\3968648659.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::SimpleAnimationComponent
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::SimpleAnimationComponent::StaticTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            void const* TTypeHelper<KRG::Animation::SimpleAnimationComponent>::DefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::SimpleAnimationComponent> TTypeHelper<KRG::Animation::SimpleAnimationComponent>::StaticTypeHelper;
        }
    }

    TypeSystem::TypeInfo const* KRG::Animation::SimpleAnimationComponent::GetTypeInfo() const
    {
        return KRG::Animation::SimpleAnimationComponent::StaticTypeInfo;
    }

    void KRG::Animation::SimpleAnimationComponent::Load( EntityModel::LoadingContext const& context, UUID requesterID )
    {
        KRG::Animation::SimpleAnimationComponent::StaticTypeInfo->m_pTypeHelper->LoadResources( context.m_pResourceSystem, requesterID, this );
        m_status = Status::Loading;
    }

    void KRG::Animation::SimpleAnimationComponent::Unload( EntityModel::LoadingContext const& context, UUID requesterID )
    {
        KRG::Animation::SimpleAnimationComponent::StaticTypeInfo->m_pTypeHelper->UnloadResources( context.m_pResourceSystem, requesterID, this );
        m_status = Status::Unloaded;
    }

    void KRG::Animation::SimpleAnimationComponent::UpdateLoading()
    {
        if( m_status == Status::Loading )
        {
            auto const resourceLoadingStatus = KRG::Animation::SimpleAnimationComponent::StaticTypeInfo->m_pTypeHelper->GetResourceLoadingStatus( this );
            if ( resourceLoadingStatus == LoadingStatus::Loading )
            {
                return; // Something is still loading so early-out
            }

            if ( resourceLoadingStatus == LoadingStatus::Failed )
            {
                m_status = EntityComponent::Status::LoadingFailed;
            }
            else
            {
                m_status = EntityComponent::Status::Loaded;
            }
        }
    }
}
