//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "E:\Git\KRG\Code\Engine\Animation\_Module\_AutoGenerated\4051905721.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::AnimationSystem
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::AnimationSystem::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Animation::AnimationSystem>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::AnimationSystem> TTypeHelper<KRG::Animation::AnimationSystem>::StaticTypeHelper;
        }
    }
}
