//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "D:\Kruger\Code\Engine\Animation\_Module\Module.h"
#include "System/Resource/ResourceSystem.h"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\1176192416.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\1181083934.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\126461494.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\1269671447.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\1407246524.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\145202680.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\1759004567.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\1897638207.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\2057524923.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\2193465449.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\2320873778.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\2353136754.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\2450972253.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\2466578237.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\2642939929.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\2659714809.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\2722157332.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\2902040491.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\3010573638.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\3088240376.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\3188765058.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\3232005270.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\3244683732.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\3247661318.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\3270222065.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\3510925642.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\3513580283.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\359294434.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\3861324641.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\3975240535.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\4092987266.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\436129338.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\485968716.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\53069741.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\732180760.cpp"
#include "D:\Kruger\Code\Engine\Animation\_Module\_AutoGenerated\869683884.cpp"

//-------------------------------------------------------------------------

void KRG::Animation::EngineModule::RegisterTypes( TypeSystem::TypeRegistry& typeRegistry )
{
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::GraphNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::AndNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::OrNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::NotNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::FloatRemapNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::FloatClampNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::FloatAbsNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::FloatEaseNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_Graph_FloatMathNode_Operator::RegisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::FloatMathNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_Graph_FloatComparisonNode_Comparison::RegisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::FloatComparisonNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::FloatRangeComparisonNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::FloatSwitchNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_Graph_EventSearchMode::RegisterEnum( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_Graph_GenericEventConditionNode_Operator::RegisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::GenericEventConditionNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::GenericEventPercentageThroughNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::FootEventConditionNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::FootstepEventPercentageThroughNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_Graph_SyncEventConditionNode_TriggerMode::RegisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::SyncEventConditionNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::CurrentSyncEventNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_AnimationPlayerComponent_PlayMode::RegisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::AnimationComponent>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::AnimationPlayerComponent>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Event>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::IDEvent>::RegisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_Graph_IDComparisonNode_Comparison::RegisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::IDComparisonNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::IDToFloatNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::BoneMaskNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::BoneMaskBlendNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::BoneMaskSelectorNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::LayerBlendNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::PassthroughNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::RootMotionOverrideNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::ZeroPoseNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::ReferencePoseNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::AnimationPoseNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::StateNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::AnimationSystem>::RegisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_Graph_ValueType::RegisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::ParameterizedBlendNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::RangedBlendNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::VelocityBlendNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::SelectorNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::AnimationSelectorNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::ConstBoolNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::ConstIDNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::ConstIntNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::ConstFloatNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::ConstVectorNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::ConstTargetNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::SpeedScaleNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::VelocityBasedSpeedScaleNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_Event_EventType::RegisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::IsTargetSetNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_Graph_TargetInfoNode_Info::RegisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::TargetInfoNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::TargetOffsetNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_FootEvent_Phase::RegisterEnum( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_FootEvent_PhaseCondition::RegisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::FootEvent>::RegisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_Graph_VectorInfoNode_Info::RegisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::VectorInfoNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::VectorNegateNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::AnimationGraphComponent>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::StateMachineNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_CoordinateSpace::RegisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::AnimationClipNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_Graph_TransitionNode_RootMotionBlend::RegisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::TransitionNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::AnimatedMeshComponent>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::StateCompletedConditionNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_Graph_TimeConditionNode_ComparisonType::RegisterEnum( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_Graph_TimeConditionNode_Operator::RegisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::TimeConditionNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::ControlParameterBoolNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::ControlParameterIDNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::ControlParameterIntNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::ControlParameterFloatNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::ControlParameterVectorNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::ControlParameterTargetNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::ControlParameterBoneMaskNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::VirtualParameterBoolNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::VirtualParameterIDNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::VirtualParameterIntNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::VirtualParameterFloatNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::VirtualParameterVectorNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::VirtualParameterTargetNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::VirtualParameterBoneMaskNode::Settings>::RegisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_PoseBlendOptions::RegisterEnum( typeRegistry );
}

void KRG::Animation::EngineModule::UnregisterTypes( TypeSystem::TypeRegistry& typeRegistry )
{
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_PoseBlendOptions::UnregisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::VirtualParameterBoneMaskNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::VirtualParameterTargetNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::VirtualParameterVectorNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::VirtualParameterFloatNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::VirtualParameterIntNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::VirtualParameterIDNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::VirtualParameterBoolNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::ControlParameterBoneMaskNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::ControlParameterTargetNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::ControlParameterVectorNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::ControlParameterFloatNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::ControlParameterIntNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::ControlParameterIDNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::ControlParameterBoolNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::TimeConditionNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_Graph_TimeConditionNode_Operator::UnregisterEnum( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_Graph_TimeConditionNode_ComparisonType::UnregisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::StateCompletedConditionNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::AnimatedMeshComponent>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::TransitionNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_Graph_TransitionNode_RootMotionBlend::UnregisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::AnimationClipNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_CoordinateSpace::UnregisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::StateMachineNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::AnimationGraphComponent>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::VectorNegateNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::VectorInfoNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_Graph_VectorInfoNode_Info::UnregisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::FootEvent>::UnregisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_FootEvent_PhaseCondition::UnregisterEnum( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_FootEvent_Phase::UnregisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::TargetOffsetNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::TargetInfoNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_Graph_TargetInfoNode_Info::UnregisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::IsTargetSetNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_Event_EventType::UnregisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::VelocityBasedSpeedScaleNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::SpeedScaleNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::ConstTargetNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::ConstVectorNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::ConstFloatNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::ConstIntNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::ConstIDNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::ConstBoolNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::AnimationSelectorNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::SelectorNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::VelocityBlendNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::RangedBlendNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::ParameterizedBlendNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_Graph_ValueType::UnregisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::AnimationSystem>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::StateNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::AnimationPoseNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::ReferencePoseNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::ZeroPoseNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::RootMotionOverrideNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::PassthroughNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::LayerBlendNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::BoneMaskSelectorNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::BoneMaskBlendNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::BoneMaskNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::IDToFloatNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::IDComparisonNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_Graph_IDComparisonNode_Comparison::UnregisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::IDEvent>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Event>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::AnimationPlayerComponent>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::AnimationComponent>::UnregisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_AnimationPlayerComponent_PlayMode::UnregisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::CurrentSyncEventNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::SyncEventConditionNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_Graph_SyncEventConditionNode_TriggerMode::UnregisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::FootstepEventPercentageThroughNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::FootEventConditionNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::GenericEventPercentageThroughNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::GenericEventConditionNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_Graph_GenericEventConditionNode_Operator::UnregisterEnum( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_Graph_EventSearchMode::UnregisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::FloatSwitchNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::FloatRangeComparisonNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::FloatComparisonNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_Graph_FloatComparisonNode_Comparison::UnregisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::FloatMathNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_Graph_FloatMathNode_Operator::UnregisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::FloatEaseNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::FloatAbsNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::FloatClampNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::FloatRemapNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::NotNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::OrNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::AndNode::Settings>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::GraphNode::Settings>::UnregisterType( typeRegistry );
}

