//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "d:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\1405685476.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::Tools_StateCompletedConditionNode
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::Tools_StateCompletedConditionNode::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Animation::Graph::Tools_StateCompletedConditionNode>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::Tools_StateCompletedConditionNode> TTypeHelper<KRG::Animation::Graph::Tools_StateCompletedConditionNode>::StaticTypeHelper;
        }
    }
}

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::Tools_TimeConditionNode
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::Tools_TimeConditionNode::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Animation::Graph::Tools_TimeConditionNode>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::Tools_TimeConditionNode> TTypeHelper<KRG::Animation::Graph::Tools_TimeConditionNode>::StaticTypeHelper;
        }
    }
}
