//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\172531865.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::SkeletonResourceDescriptor
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::SkeletonResourceDescriptor::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            void const* TTypeHelper<KRG::Animation::SkeletonResourceDescriptor>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::SkeletonResourceDescriptor> TTypeHelper<KRG::Animation::SkeletonResourceDescriptor>::StaticTypeHelper;
        }
    }
}
