//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\2174867705.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::StateMachineToolsGraph
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::StateMachineToolsGraph::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Animation::Graph::StateMachineToolsGraph>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::StateMachineToolsGraph> TTypeHelper<KRG::Animation::Graph::StateMachineToolsGraph>::StaticTypeHelper;
        }
    }
}
