//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\2400828525.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Tools::EventTrackInfo
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Tools::EventTrackInfo::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            void const* TTypeHelper<KRG::Animation::Tools::EventTrackInfo>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Tools::EventTrackInfo> TTypeHelper<KRG::Animation::Tools::EventTrackInfo>::StaticTypeHelper;
        }
    }
}
