//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\2677063852.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::AnimationGraphVariationResourceDescriptor
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::AnimationGraphVariationResourceDescriptor::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Animation::AnimationGraphVariationResourceDescriptor>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::AnimationGraphVariationResourceDescriptor> TTypeHelper<KRG::Animation::AnimationGraphVariationResourceDescriptor>::StaticTypeHelper;
        }
    }
}
