//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\3044923915.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::ToolsNode
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::ToolsNode::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Animation::Graph::ToolsNode>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::ToolsNode> TTypeHelper<KRG::Animation::Graph::ToolsNode>::StaticTypeHelper;
        }
    }
}
