//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "E:\Git\KRG\Code\Tools\Animation\_Module\_AutoGenerated\3446516495.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::Tools_RootMotionOverrideNode
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::Tools_RootMotionOverrideNode::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Animation::Graph::Tools_RootMotionOverrideNode>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::Tools_RootMotionOverrideNode> TTypeHelper<KRG::Animation::Graph::Tools_RootMotionOverrideNode>::StaticTypeHelper;
        }
    }
}
