//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\3446627217.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::FlowToolsNode
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::FlowToolsNode::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Animation::Graph::FlowToolsNode>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::FlowToolsNode> TTypeHelper<KRG::Animation::Graph::FlowToolsNode>::StaticTypeHelper;
        }
    }
}

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::DataSlotToolsNode::OverrideValue
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::DataSlotToolsNode::OverrideValue::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Animation::Graph::DataSlotToolsNode::OverrideValue>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::DataSlotToolsNode::OverrideValue> TTypeHelper<KRG::Animation::Graph::DataSlotToolsNode::OverrideValue>::StaticTypeHelper;
        }
    }
}

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::DataSlotToolsNode
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::DataSlotToolsNode::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Animation::Graph::DataSlotToolsNode>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::DataSlotToolsNode> TTypeHelper<KRG::Animation::Graph::DataSlotToolsNode>::StaticTypeHelper;
        }
    }
}
