//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "E:\Git\KRG\Code\Tools\Animation\_Module\_AutoGenerated\3824974149.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::Tools_EntryStateOverrideConditionsNode
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::Tools_EntryStateOverrideConditionsNode::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Animation::Graph::Tools_EntryStateOverrideConditionsNode>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::Tools_EntryStateOverrideConditionsNode> TTypeHelper<KRG::Animation::Graph::Tools_EntryStateOverrideConditionsNode>::StaticTypeHelper;
        }
    }
}

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::Tools_EntryStateOverrideGraph
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::Tools_EntryStateOverrideGraph::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Animation::Graph::Tools_EntryStateOverrideGraph>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::Tools_EntryStateOverrideGraph> TTypeHelper<KRG::Animation::Graph::Tools_EntryStateOverrideGraph>::StaticTypeHelper;
        }
    }
}

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::Tools_EntryStateOverrideNode
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::Tools_EntryStateOverrideNode::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Animation::Graph::Tools_EntryStateOverrideNode>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::Tools_EntryStateOverrideNode> TTypeHelper<KRG::Animation::Graph::Tools_EntryStateOverrideNode>::StaticTypeHelper;
        }
    }
}
