//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "E:\Git\KRG\Code\Tools\Animation\_Module\_AutoGenerated\422246967.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::Tools_FloatRemapNode
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::Tools_FloatRemapNode::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Animation::Graph::Tools_FloatRemapNode>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::Tools_FloatRemapNode> TTypeHelper<KRG::Animation::Graph::Tools_FloatRemapNode>::StaticTypeHelper;
        }
    }
}

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::Tools_FloatClampNode
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::Tools_FloatClampNode::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Animation::Graph::Tools_FloatClampNode>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::Tools_FloatClampNode> TTypeHelper<KRG::Animation::Graph::Tools_FloatClampNode>::StaticTypeHelper;
        }
    }
}

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::Tools_FloatAbsNode
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::Tools_FloatAbsNode::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Animation::Graph::Tools_FloatAbsNode>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::Tools_FloatAbsNode> TTypeHelper<KRG::Animation::Graph::Tools_FloatAbsNode>::StaticTypeHelper;
        }
    }
}

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::Tools_FloatEaseNode
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::Tools_FloatEaseNode::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Animation::Graph::Tools_FloatEaseNode>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::Tools_FloatEaseNode> TTypeHelper<KRG::Animation::Graph::Tools_FloatEaseNode>::StaticTypeHelper;
        }
    }
}

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::Tools_FloatMathNode
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::Tools_FloatMathNode::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Animation::Graph::Tools_FloatMathNode>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::Tools_FloatMathNode> TTypeHelper<KRG::Animation::Graph::Tools_FloatMathNode>::StaticTypeHelper;
        }
    }
}

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::Tools_FloatComparisonNode
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::Tools_FloatComparisonNode::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Animation::Graph::Tools_FloatComparisonNode>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::Tools_FloatComparisonNode> TTypeHelper<KRG::Animation::Graph::Tools_FloatComparisonNode>::StaticTypeHelper;
        }
    }
}

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::Tools_FloatRangeComparisonNode
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::Tools_FloatRangeComparisonNode::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Animation::Graph::Tools_FloatRangeComparisonNode>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::Tools_FloatRangeComparisonNode> TTypeHelper<KRG::Animation::Graph::Tools_FloatRangeComparisonNode>::StaticTypeHelper;
        }
    }
}

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::Tools_FloatSwitchNode
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::Tools_FloatSwitchNode::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Animation::Graph::Tools_FloatSwitchNode>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::Tools_FloatSwitchNode> TTypeHelper<KRG::Animation::Graph::Tools_FloatSwitchNode>::StaticTypeHelper;
        }
    }
}
