//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "E:\Git\KRG\Code\Tools\Animation\_Module\_AutoGenerated\650847995.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::Animation::Graph::StateMachineGraph
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Animation::Graph::StateMachineGraph::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Animation::Graph::StateMachineGraph>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Animation::Graph::StateMachineGraph> TTypeHelper<KRG::Animation::Graph::StateMachineGraph>::StaticTypeHelper;
        }
    }
}
