//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "D:\Kruger\Code\Tools\Animation\_Module\Module.h"
#include "System/Resource/ResourceSystem.h"
#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\172531865.cpp"
#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\2400828525.cpp"
#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\3637919814.cpp"

//-------------------------------------------------------------------------

void KRG::Animation::ToolsModule::RegisterTypes( TypeSystem::TypeRegistry& typeRegistry )
{
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::SkeletonResourceDescriptor>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Tools::EventTrackInfo>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::AnimationResourceDescriptor>::RegisterType( typeRegistry );
}

void KRG::Animation::ToolsModule::UnregisterTypes( TypeSystem::TypeRegistry& typeRegistry )
{
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::AnimationResourceDescriptor>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Tools::EventTrackInfo>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::SkeletonResourceDescriptor>::UnregisterType( typeRegistry );
}

