//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "D:\Kruger\Code\Tools\Animation\_Module\Module.h"
#include "System/Resource/ResourceSystem.h"
#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\1307461330.cpp"
#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\1337679804.cpp"
#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\1405685476.cpp"
#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\1493528847.cpp"
#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\1511552779.cpp"
#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\1518661729.cpp"
#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\1582875233.cpp"
#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\1598129294.cpp"
#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\1768561785.cpp"
#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\1859853509.cpp"
#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\1925337640.cpp"
#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\1947544747.cpp"
#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\2163439713.cpp"
#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\2351521578.cpp"
#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\2738708458.cpp"
#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\2759168123.cpp"
#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\3002288438.cpp"
#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\3141718644.cpp"
#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\3385835077.cpp"
#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\3434921185.cpp"
#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\3476169127.cpp"
#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\3616846488.cpp"
#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\3696221119.cpp"
#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\3758106294.cpp"
#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\3827554083.cpp"
#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\3958226852.cpp"
#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\4247503357.cpp"
#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\609102739.cpp"
#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\63786333.cpp"
#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\640925531.cpp"
#include "D:\Kruger\Code\Tools\Animation\_Module\_AutoGenerated\856753736.cpp"

//-------------------------------------------------------------------------

void KRG::Animation::ToolsModule::RegisterTypes( TypeSystem::TypeRegistry& typeRegistry )
{
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_GraphNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_RootMotionOverrideNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_IsTargetSetNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_TargetInfoNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_TargetOffsetNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_TransitionNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_GlobalTransitionNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_TransitionConduitNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::FlowGraph>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::GlobalTransitionsToolsGraph>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_GlobalTransitionsNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::AnimationClipResourceDescriptor>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::EventItem>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::EventTrack>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_ControlParameterNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_ControlParameterReferenceNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_VirtualParameterNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_VirtualParameterReferenceNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_StateCompletedConditionNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_TimeConditionNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::StateMachineGraph>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_StateMachineNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_StateLayerDataNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_StateBaseNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_StateNode::TimedStateEvent>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_StateNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_OffStateNode>::RegisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_Graph_GraphType::RegisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_GenericEventConditionNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_GenericEventPercentageThroughNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_FootEventConditionNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_FootstepEventPercentageThroughNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_SyncEventConditionNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_CurrentSyncEventNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_SpeedScaleNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_VelocityBasedSpeedScaleNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_ResultNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_IDComparisonNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_IDToFloatNode::Mapping>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_IDToFloatNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_DataSlotNode::OverrideValue>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_DataSlotNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_FloatRemapNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_FloatClampNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_FloatAbsNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_FloatEaseNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_FloatMathNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_FloatComparisonNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_FloatRangeComparisonNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_FloatSwitchNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_VectorInfoNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_VectorNegateNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_AndNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_OrNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_NotNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_ConstBoolNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_ConstIDNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_ConstIntNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_ConstFloatNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_ConstVectorNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_ConstTargetNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::AnimationGraphVariationResourceDescriptor>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_ParameterizedBlendNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_RangedBlendNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_VelocityBlendNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_LayerSettingsNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_LayerNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_SelectorConditionNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_SelectorNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_BoneMaskNode::ToolsBoneWeight>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_BoneMaskNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_BoneMaskBlendNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_BoneMaskSelectorNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Variation>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_AnimationClipNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_ZeroPoseNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_ReferencePoseNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_AnimationPoseNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::SkeletonResourceDescriptor>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_EntryStateOverrideConditionsNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_EntryStateOverrideGraph>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_EntryStateOverrideNode>::RegisterType( typeRegistry );
}

void KRG::Animation::ToolsModule::UnregisterTypes( TypeSystem::TypeRegistry& typeRegistry )
{
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_EntryStateOverrideNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_EntryStateOverrideGraph>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_EntryStateOverrideConditionsNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::SkeletonResourceDescriptor>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_AnimationPoseNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_ReferencePoseNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_ZeroPoseNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_AnimationClipNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Variation>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_BoneMaskSelectorNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_BoneMaskBlendNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_BoneMaskNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_BoneMaskNode::ToolsBoneWeight>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_SelectorNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_SelectorConditionNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_LayerNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_LayerSettingsNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_VelocityBlendNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_RangedBlendNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_ParameterizedBlendNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::AnimationGraphVariationResourceDescriptor>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_ConstTargetNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_ConstVectorNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_ConstFloatNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_ConstIntNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_ConstIDNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_ConstBoolNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_NotNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_OrNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_AndNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_VectorNegateNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_VectorInfoNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_FloatSwitchNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_FloatRangeComparisonNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_FloatComparisonNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_FloatMathNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_FloatEaseNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_FloatAbsNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_FloatClampNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_FloatRemapNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_DataSlotNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_DataSlotNode::OverrideValue>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_IDToFloatNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_IDToFloatNode::Mapping>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_IDComparisonNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_ResultNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_VelocityBasedSpeedScaleNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_SpeedScaleNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_CurrentSyncEventNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_SyncEventConditionNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_FootstepEventPercentageThroughNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_FootEventConditionNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_GenericEventPercentageThroughNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_GenericEventConditionNode>::UnregisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Animation_Graph_GraphType::UnregisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_OffStateNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_StateNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_StateNode::TimedStateEvent>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_StateBaseNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_StateLayerDataNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_StateMachineNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::StateMachineGraph>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_TimeConditionNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_StateCompletedConditionNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_VirtualParameterReferenceNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_VirtualParameterNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_ControlParameterReferenceNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_ControlParameterNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::EventTrack>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::EventItem>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::AnimationClipResourceDescriptor>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_GlobalTransitionsNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::GlobalTransitionsToolsGraph>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::FlowGraph>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_TransitionConduitNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_GlobalTransitionNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_TransitionNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_TargetOffsetNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_TargetInfoNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_IsTargetSetNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_RootMotionOverrideNode>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Animation::Graph::Tools_GraphNode>::UnregisterType( typeRegistry );
}

