//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "D:\Kruger\Code\Engine\Core\_Module\_AutoGenerated\1374616486.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::SystemDebugView
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::SystemDebugView::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::SystemDebugView>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::SystemDebugView> TTypeHelper<KRG::SystemDebugView>::StaticTypeHelper;
        }
    }
}
