//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "E:\Git\KRG\Code\Engine\Core\_Module\_AutoGenerated\1438148119.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::Input::InputDebugView
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Input::InputDebugView::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Input::InputDebugView>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Input::InputDebugView> TTypeHelper<KRG::Input::InputDebugView>::StaticTypeHelper;
        }
    }
}
