//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "D:\Kruger\Code\Engine\Core\_Module\_AutoGenerated\2345825012.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::CameraWorldSystem
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::CameraWorldSystem::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::CameraWorldSystem>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::CameraWorldSystem> TTypeHelper<KRG::CameraWorldSystem>::StaticTypeHelper;
        }
    }
}
