//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "E:\Git\KRG\Code\Engine\Core\_Module\_AutoGenerated\2820898296.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::SpatialEntityComponent
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::SpatialEntityComponent::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::SpatialEntityComponent>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::SpatialEntityComponent> TTypeHelper<KRG::SpatialEntityComponent>::StaticTypeHelper;
        }
    }
}
