//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "D:\Kruger\Code\Engine\Core\_Module\_AutoGenerated\331089537.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::Resource::ResourceDebugView
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Resource::ResourceDebugView::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Resource::ResourceDebugView>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Resource::ResourceDebugView> TTypeHelper<KRG::Resource::ResourceDebugView>::StaticTypeHelper;
        }
    }
}
