//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "E:\Git\KRG\Code\Engine\Core\_Module\_AutoGenerated\347253001.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::IEntitySystem
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::IEntitySystem::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::IEntitySystem>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::IEntitySystem> TTypeHelper<KRG::IEntitySystem>::StaticTypeHelper;
        }
    }
}
