//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "D:\Kruger\Code\Engine\Core\_Module\_AutoGenerated\3895633844.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::IWorldEntitySystem
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::IWorldEntitySystem::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::IWorldEntitySystem>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::IWorldEntitySystem> TTypeHelper<KRG::IWorldEntitySystem>::StaticTypeHelper;
        }
    }
}
