//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "E:\Git\KRG\Code\Engine\Core\_Module\_AutoGenerated\4193846163.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::EntityWorldDebugView
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::EntityWorldDebugView::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::EntityWorldDebugView>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::EntityWorldDebugView> TTypeHelper<KRG::EntityWorldDebugView>::StaticTypeHelper;
        }
    }
}
