//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "E:\Git\KRG\Code\Engine\Core\_Module\_AutoGenerated\621982902.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::EntityDebugView
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::EntityDebugView::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::EntityDebugView>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::EntityDebugView> TTypeHelper<KRG::EntityDebugView>::StaticTypeHelper;
        }
    }
}
