//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "D:\Kruger\Code\Engine\Core\_Module\Module.h"
#include "System/Resource/ResourceSystem.h"
#include "D:\Kruger\Code\Engine\Core\_Module\_AutoGenerated\2571240691.cpp"

//-------------------------------------------------------------------------

void KRG::EngineCore::EngineModule::RegisterTypes( TypeSystem::TypeRegistry& typeRegistry )
{
    TypeSystem::EnumHelpers::EnumHelper_KRG_Math_Easing_Type::RegisterEnum( typeRegistry );
}

void KRG::EngineCore::EngineModule::UnregisterTypes( TypeSystem::TypeRegistry& typeRegistry )
{
    TypeSystem::EnumHelpers::EnumHelper_KRG_Math_Easing_Type::UnregisterEnum( typeRegistry );
}

