//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "E:\Git\KRG\Code\Engine\Core\_Module\Module.h"
#include "System/Resource/ResourceSystem.h"
#include "E:\Git\KRG\Code\Engine\Core\_Module\_AutoGenerated\1169897667.cpp"
#include "E:\Git\KRG\Code\Engine\Core\_Module\_AutoGenerated\1369289556.cpp"
#include "E:\Git\KRG\Code\Engine\Core\_Module\_AutoGenerated\1438148119.cpp"
#include "E:\Git\KRG\Code\Engine\Core\_Module\_AutoGenerated\2041177721.cpp"
#include "E:\Git\KRG\Code\Engine\Core\_Module\_AutoGenerated\2450634364.cpp"
#include "E:\Git\KRG\Code\Engine\Core\_Module\_AutoGenerated\2820898296.cpp"
#include "E:\Git\KRG\Code\Engine\Core\_Module\_AutoGenerated\2883414684.cpp"
#include "E:\Git\KRG\Code\Engine\Core\_Module\_AutoGenerated\3059223877.cpp"
#include "E:\Git\KRG\Code\Engine\Core\_Module\_AutoGenerated\347253001.cpp"
#include "E:\Git\KRG\Code\Engine\Core\_Module\_AutoGenerated\3918574432.cpp"
#include "E:\Git\KRG\Code\Engine\Core\_Module\_AutoGenerated\3957499939.cpp"
#include "E:\Git\KRG\Code\Engine\Core\_Module\_AutoGenerated\4129147022.cpp"
#include "E:\Git\KRG\Code\Engine\Core\_Module\_AutoGenerated\4193846163.cpp"
#include "E:\Git\KRG\Code\Engine\Core\_Module\_AutoGenerated\480868206.cpp"
#include "E:\Git\KRG\Code\Engine\Core\_Module\_AutoGenerated\621982902.cpp"

//-------------------------------------------------------------------------

void KRG::EngineCore::EngineModule::RegisterTypes( TypeSystem::TypeRegistry& typeRegistry )
{
    TypeSystem::EnumHelpers::EnumHelper_KRG_CameraComponent_ProjectionType::RegisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::EntityComponent>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::SpatialEntityComponent>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::CameraComponent>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::IWorldEntitySystem>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::CameraWorldSystem>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::EntityWorldDebugView>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Camera::CameraDebugView>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Input::InputDebugView>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::SystemDebugView>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Resource::ResourceDebugView>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::EntityDebugView>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Entity>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::IEntitySystem>::RegisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_Math_Easing_Type::RegisterEnum( typeRegistry );
}

void KRG::EngineCore::EngineModule::UnregisterTypes( TypeSystem::TypeRegistry& typeRegistry )
{
    TypeSystem::EnumHelpers::EnumHelper_KRG_Math_Easing_Type::UnregisterEnum( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::IEntitySystem>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Entity>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::EntityDebugView>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Resource::ResourceDebugView>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::SystemDebugView>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Input::InputDebugView>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Camera::CameraDebugView>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::EntityWorldDebugView>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::CameraWorldSystem>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::IWorldEntitySystem>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::CameraComponent>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::SpatialEntityComponent>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::EntityComponent>::UnregisterType( typeRegistry );
    TypeSystem::EnumHelpers::EnumHelper_KRG_CameraComponent_ProjectionType::UnregisterEnum( typeRegistry );
}

