//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "E:\Git\KRG\Code\Engine\Navmesh\_Module\_AutoGenerated\352136731.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::Navmesh::NavmeshDebugView
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Navmesh::NavmeshDebugView::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Navmesh::NavmeshDebugView>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Navmesh::NavmeshDebugView> TTypeHelper<KRG::Navmesh::NavmeshDebugView>::StaticTypeHelper;
        }
    }
}
