//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "D:\Kruger\Code\Engine\Navmesh\_Module\_AutoGenerated\3975288761.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::Navmesh::NavmeshWorldSystem
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Navmesh::NavmeshWorldSystem::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Navmesh::NavmeshWorldSystem>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Navmesh::NavmeshWorldSystem> TTypeHelper<KRG::Navmesh::NavmeshWorldSystem>::StaticTypeHelper;
        }
    }
}
