//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "E:\Git\KRG\Code\Engine\Navmesh\_Module\_AutoGenerated\899016312.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::Navmesh::NavmeshComponent
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Navmesh::NavmeshComponent::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::Navmesh::NavmeshComponent>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Navmesh::NavmeshComponent> TTypeHelper<KRG::Navmesh::NavmeshComponent>::StaticTypeHelper;
        }
    }

    void KRG::Navmesh::NavmeshComponent::Load( EntityModel::LoadingContext const& context, UUID requesterID )
    {
        KRG::Navmesh::NavmeshComponent::s_pTypeInfo->m_pTypeHelper->LoadResources( context.m_pResourceSystem, requesterID, this );
        m_status = Status::Loading;
    }

    void KRG::Navmesh::NavmeshComponent::Unload( EntityModel::LoadingContext const& context, UUID requesterID )
    {
        KRG::Navmesh::NavmeshComponent::s_pTypeInfo->m_pTypeHelper->UnloadResources( context.m_pResourceSystem, requesterID, this );
        m_status = Status::Unloaded;
    }

    void KRG::Navmesh::NavmeshComponent::UpdateLoading()
    {
        if( m_status == Status::Loading )
        {
            auto const resourceLoadingStatus = KRG::Navmesh::NavmeshComponent::s_pTypeInfo->m_pTypeHelper->GetResourceLoadingStatus( this );
            if ( resourceLoadingStatus == LoadingStatus::Loading )
            {
                return; // Something is still loading so early-out
            }

            if ( resourceLoadingStatus == LoadingStatus::Failed )
            {
                m_status = EntityComponent::Status::LoadingFailed;
            }
            else
            {
                m_status = EntityComponent::Status::Loaded;
            }
        }
    }
}
