//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "D:\Kruger\Code\Engine\Navmesh\_Module\Module.h"
#include "System/Resource/ResourceSystem.h"
#include "D:\Kruger\Code\Engine\Navmesh\_Module\_AutoGenerated\3664162683.cpp"
#include "D:\Kruger\Code\Engine\Navmesh\_Module\_AutoGenerated\3975288761.cpp"
#include "D:\Kruger\Code\Engine\Navmesh\_Module\_AutoGenerated\47081010.cpp"
#include "D:\Kruger\Code\Engine\Navmesh\_Module\_AutoGenerated\478697081.cpp"

//-------------------------------------------------------------------------

void KRG::Navmesh::EngineModule::RegisterTypes( TypeSystem::TypeRegistry& typeRegistry )
{
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Navmesh::NavmeshDebugView>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Navmesh::NavmeshComponent>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Navmesh::NavmeshWorldSystem>::RegisterType( typeRegistry );
}

void KRG::Navmesh::EngineModule::UnregisterTypes( TypeSystem::TypeRegistry& typeRegistry )
{
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Navmesh::NavmeshWorldSystem>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Navmesh::NavmeshComponent>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Navmesh::NavmeshDebugView>::UnregisterType( typeRegistry );
}

