//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "D:\Kruger\Code\Tools\Resource\_Module\_AutoGenerated\1600369293.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::Resource::ResourceDescriptor
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::Resource::ResourceDescriptor::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            void const* TTypeHelper<KRG::Resource::ResourceDescriptor>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::Resource::ResourceDescriptor> TTypeHelper<KRG::Resource::ResourceDescriptor>::StaticTypeHelper;
        }
    }
}
