//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "d:\Kruger\Code\Tools\Core\_Module\_AutoGenerated\2600276853.h"

//-------------------------------------------------------------------------
// TypeHelper: KRG::GraphEditor::SM::Node
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::GraphEditor::SM::Node::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::GraphEditor::SM::Node>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::GraphEditor::SM::Node> TTypeHelper<KRG::GraphEditor::SM::Node>::StaticTypeHelper;
        }
    }
}

//-------------------------------------------------------------------------
// TypeHelper: KRG::GraphEditor::SM::State
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::GraphEditor::SM::State::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::GraphEditor::SM::State>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::GraphEditor::SM::State> TTypeHelper<KRG::GraphEditor::SM::State>::StaticTypeHelper;
        }
    }
}

//-------------------------------------------------------------------------
// TypeHelper: KRG::GraphEditor::SM::TransitionConduit
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::GraphEditor::SM::TransitionConduit::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::GraphEditor::SM::TransitionConduit>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::GraphEditor::SM::TransitionConduit> TTypeHelper<KRG::GraphEditor::SM::TransitionConduit>::StaticTypeHelper;
        }
    }
}

//-------------------------------------------------------------------------
// TypeHelper: KRG::GraphEditor::StateMachineGraph
//-------------------------------------------------------------------------

namespace KRG
{
    TypeSystem::TypeInfo const* KRG::GraphEditor::StateMachineGraph::s_pTypeInfo = nullptr;
    namespace TypeSystem
    {
        namespace TypeHelpers
        {
            IRegisteredType const* TTypeHelper<KRG::GraphEditor::StateMachineGraph>::s_pDefaultTypeInstancePtr = nullptr;

            TTypeHelper<KRG::GraphEditor::StateMachineGraph> TTypeHelper<KRG::GraphEditor::StateMachineGraph>::StaticTypeHelper;
        }
    }
}
