//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "D:\Kruger\Code\Tools\Core\_Module\Module.h"
#include "System/Resource/ResourceSystem.h"
#include "D:\Kruger\Code\Tools\Core\_Module\_AutoGenerated\1039980441.cpp"
#include "D:\Kruger\Code\Tools\Core\_Module\_AutoGenerated\1140429351.cpp"
#include "D:\Kruger\Code\Tools\Core\_Module\_AutoGenerated\1912109448.cpp"
#include "D:\Kruger\Code\Tools\Core\_Module\_AutoGenerated\2600276853.cpp"
#include "D:\Kruger\Code\Tools\Core\_Module\_AutoGenerated\3679790120.cpp"

//-------------------------------------------------------------------------

void KRG::ToolsModule::RegisterTypes( TypeSystem::TypeRegistry& typeRegistry )
{
    TypeSystem::TypeHelpers::TTypeHelper<KRG::GraphEditor::BaseNode>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::GraphEditor::Flow::Node>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::GraphEditor::BaseGraph>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::GraphEditor::FlowGraph>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Timeline::TrackItem>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Timeline::Track>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Resource::ResourceDescriptor>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::GraphEditor::SM::Node>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::GraphEditor::SM::State>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::GraphEditor::SM::TransitionConduit>::RegisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::GraphEditor::StateMachineGraph>::RegisterType( typeRegistry );
}

void KRG::ToolsModule::UnregisterTypes( TypeSystem::TypeRegistry& typeRegistry )
{
    TypeSystem::TypeHelpers::TTypeHelper<KRG::GraphEditor::StateMachineGraph>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::GraphEditor::SM::TransitionConduit>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::GraphEditor::SM::State>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::GraphEditor::SM::Node>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Resource::ResourceDescriptor>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Timeline::Track>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Timeline::TrackItem>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::GraphEditor::FlowGraph>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::GraphEditor::BaseGraph>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::GraphEditor::Flow::Node>::UnregisterType( typeRegistry );
    TypeSystem::TypeHelpers::TTypeHelper<KRG::GraphEditor::BaseNode>::UnregisterType( typeRegistry );
}

