//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit
//-------------------------------------------------------------------------

#include "D:\Kruger\Code\Compilers\Physics\_Module\Module.h"
#include "System/Resource/ResourceSystem.h"
#include "D:\Kruger\Code\Compilers\Physics\_Module\_AutoGenerated\3500931963.cpp"

//-------------------------------------------------------------------------

void KRG::Physics::ResourceCompilerModule::RegisterTypes( TypeSystem::TypeRegistry& typeRegistry )
{
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Physics::PhysicsGeometryResourceDescriptor>::RegisterType( typeRegistry );
}

void KRG::Physics::ResourceCompilerModule::UnregisterTypes( TypeSystem::TypeRegistry& typeRegistry )
{
    TypeSystem::TypeHelpers::TTypeHelper<KRG::Physics::PhysicsGeometryResourceDescriptor>::UnregisterType( typeRegistry );
}

